server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index Luis&SantiCO.html;

    location / {
        try_files $uri $uri/ /Luis&SantiCO.html;
    }

    # Cache de assets estáticos
    location ~* \.(js|jsx|css|png|jpg|svg|ico|woff2)$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}
